# Generated by Django 4.2.1 on 2023-06-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='date_submitted',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='joke',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='joke',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
