# Generated by Django 4.2.1 on 2023-06-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0003_rename_setup_joke_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='proceed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
            ],
        ),
    ]
