# Generated by Django 4.2.1 on 2023-06-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0004_proceed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceed',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
